CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL
);
INSERT INTO products (id, name, brand, price) VALUES (1, 'iPhone 13', 'Apple', 670);
INSERT INTO products (id, name, brand, price) VALUES (2, 'Galaxy S21', 'Samsung', 820);
INSERT INTO products (id, name, brand, price) VALUES (3, 'Pixel 6', 'Google', 880);
INSERT INTO products (id, name, brand, price) VALUES (4, 'Mate 40 Pro', 'Huawei', 770);
INSERT INTO products (id, name, brand, price) VALUES (5, 'Xperia 1 III', 'Sony', 780);
INSERT INTO products (id, name, brand, price) VALUES (6, 'Legion Phone Duel 2', 'Lenovo', 750);
INSERT INTO products (id, name, brand, price) VALUES (7, 'ROG Phone 5', 'Asus', 930);
INSERT INTO products (id, name, brand, price) VALUES (8, 'Mi 11 Ultra', 'Xiaomi', 820);
INSERT INTO products (id, name, brand, price) VALUES (9, 'V60 ThinQ', 'LG', 790);
INSERT INTO products (id, name, brand, price) VALUES (10, 'Nord 2', 'OnePlus', 780);
INSERT INTO products (id, name, brand, price) VALUES (11, 'Find X3 Pro', 'Oppo', 960);
INSERT INTO products (id, name, brand, price) VALUES (12, 'Poco X3 NFC', 'Poco', 900);
INSERT INTO products (id, name, brand, price) VALUES (13, 'Black Shark 4', 'Xiaomi', 760);
INSERT INTO products (id, name, brand, price) VALUES (14, 'Reno5 Pro 5G', 'Oppo', 820);
INSERT INTO products (id, name, brand, price) VALUES (15, 'Moto G Power (2021)', 'Motorola', 720);
INSERT INTO products (id, name, brand, price) VALUES (16, 'Galaxy A52', 'Samsung', 660);
INSERT INTO products (id, name, brand, price) VALUES (17, 'Zenfone 7 Pro', 'Asus', 630);
INSERT INTO products (id, name, brand, price) VALUES (18, 'Velvet', 'LG', 670);
INSERT INTO products (id, name, brand, price) VALUES (19, 'Xperia 5 II', 'Sony', 850);
INSERT INTO products (id, name, brand, price) VALUES (20, 'Wing 5G', 'LG', 800);
INSERT INTO products (id, name, brand, price) VALUES (21, 'Galaxy Z Fold2', 'Samsung', 610);
INSERT INTO products (id, name, brand, price) VALUES (22, 'Surface Duo', 'Microsoft', 860);
INSERT INTO products (id, name, brand, price) VALUES (23, 'Legion Pro', 'Lenovo', 940);
INSERT INTO products (id, name, brand, price) VALUES (24, 'ROG Phone 3', 'Asus', 800);
INSERT INTO products (id, name, brand, price) VALUES (25, 'Velvet 5G', 'LG', 750);
INSERT INTO products (id, name, brand, price) VALUES (26, 'Xperia 10 II', 'Sony', 640);
INSERT INTO products (id, name, brand, price) VALUES (27, 'Galaxy Note20 Ultra', 'Samsung', 700);
INSERT INTO products (id, name, brand, price) VALUES (28, 'Moto G 5G Plus', 'Motorola', 600);
INSERT INTO products (id, name, brand, price) VALUES (29, 'Mi 11 Ultra', 'Xiaomi', 890);
INSERT INTO products (id, name, brand, price) VALUES (30, 'Zenfone 7', 'Asus', 800);
INSERT INTO products (id, name, brand, price) VALUES (31, 'Galaxy Z Flip', 'Samsung', 880);
INSERT INTO products (id, name, brand, price) VALUES (32, 'V60 ThinQ 5G', 'LG', 860);
INSERT INTO products (id, name, brand, price) VALUES (33, 'Xperia 1 II', 'Sony', 940);
INSERT INTO products (id, name, brand, price) VALUES (34, 'Find X2 Pro', 'Oppo', 820);
INSERT INTO products (id, name, brand, price) VALUES (35, 'Black Shark 3 Pro', 'Xiaomi', 940);
INSERT INTO products (id, name, brand, price) VALUES (36, 'Galaxy S20 Ultra', 'Samsung', 720);
INSERT INTO products (id, name, brand, price) VALUES (37, 'ROG Phone II', 'Asus', 940);
INSERT INTO products (id, name, brand, price) VALUES (38, 'Mate 30 Pro 5G', 'Huawei', 760);
INSERT INTO products (id, name, brand, price) VALUES (39, 'Moto Z4', 'Motorola', 720);
INSERT INTO products (id, name, brand, price) VALUES (40, 'Mi 9', 'Xiaomi', 780);
INSERT INTO products (id, name, brand, price) VALUES (41, 'Zenfone 6', 'Asus', 670);
INSERT INTO products (id, name, brand, price) VALUES (42, 'Xperia 1', 'Sony', 950);
INSERT INTO products (id, name, brand, price) VALUES (43, 'Galaxy S10', 'Samsung', 670);
INSERT INTO products (id, name, brand, price) VALUES (44, 'V50 ThinQ 5G', 'LG', 850);
INSERT INTO products (id, name, brand, price) VALUES (45, 'P30 Pro', 'Huawei', 800);
INSERT INTO products (id, name, brand, price) VALUES (46, 'Moto G7 Power', 'Motorola', 780);
INSERT INTO products (id, name, brand, price) VALUES (47, 'Mi Mix 3', 'Xiaomi', 620);
INSERT INTO products (id, name, brand, price) VALUES (48, 'ROG Phone', 'Asus', 780);
INSERT INTO products (id, name, brand, price) VALUES (49, 'Mate 20 Pro', 'Huawei', 930);
INSERT INTO products (id, name, brand, price) VALUES (50, 'Galaxy Note9', 'Samsung', 850);
INSERT INTO products (id, name, brand, price) VALUES (51, 'iPhone 12', 'Apple', 620);
INSERT INTO products (id, name, brand, price) VALUES (52, 'Galaxy S20', 'Samsung', 650);
INSERT INTO products (id, name, brand, price) VALUES (53, 'Pixel 5', 'Google', 790);
INSERT INTO products (id, name, brand, price) VALUES (54, 'P40 Pro', 'Huawei', 660);
INSERT INTO products (id, name, brand, price) VALUES (55, 'Xperia 5 III', 'Sony', 750);
INSERT INTO products (id, name, brand, price) VALUES (56, 'Legion Phone Duel', 'Lenovo', 980);
INSERT INTO products (id, name, brand, price) VALUES (57, 'ROG Phone 3', 'Asus', 840);
INSERT INTO products (id, name, brand, price) VALUES (58, 'Mi 10 Ultra', 'Xiaomi', 940);
INSERT INTO products (id, name, brand, price) VALUES (59, 'V50 ThinQ', 'LG', 600);
INSERT INTO products (id, name, brand, price) VALUES (60, 'Nord', 'OnePlus', 830);
INSERT INTO products (id, name, brand, price) VALUES (61, 'Find X2', 'Oppo', 730);
INSERT INTO products (id, name, brand, price) VALUES (62, 'Poco X2', 'Poco', 640);
INSERT INTO products (id, name, brand, price) VALUES (63, 'Black Shark 3', 'Xiaomi', 610);
INSERT INTO products (id, name, brand, price) VALUES (64, 'Reno4 Pro 5G', 'Oppo', 970);
INSERT INTO products (id, name, brand, price) VALUES (65, 'Moto G Power (2020)', 'Motorola', 960);
INSERT INTO products (id, name, brand, price) VALUES (66, 'Galaxy A51', 'Samsung', 600);
INSERT INTO products (id, name, brand, price) VALUES (67, 'Zenfone 6Z', 'Asus', 840);
INSERT INTO products (id, name, brand, price) VALUES (68, 'Velvet 4G', 'LG', 810);
INSERT INTO products (id, name, brand, price) VALUES (69, 'Xperia 10 III', 'Sony', 980);
INSERT INTO products (id, name, brand, price) VALUES (70, 'Wing 4G', 'LG', 700);
INSERT INTO products (id, name, brand, price) VALUES (71, 'Galaxy Z Flip 5G', 'Samsung', 870);
INSERT INTO products (id, name, brand, price) VALUES (72, 'Surface Duo 2', 'Microsoft', 660);
INSERT INTO products (id, name, brand, price) VALUES (73, 'Legion Duel', 'Lenovo', 680);
INSERT INTO products (id, name, brand, price) VALUES (74, 'ROG Phone II', 'Asus', 610);
INSERT INTO products (id, name, brand, price) VALUES (75, 'Velvet 4G', 'LG', 600);
INSERT INTO products (id, name, brand, price) VALUES (76, 'Xperia L4', 'Sony', 800);
INSERT INTO products (id, name, brand, price) VALUES (77, 'Galaxy Note10', 'Samsung', 960);
INSERT INTO products (id, name, brand, price) VALUES (78, 'Moto G 5G', 'Motorola', 870);
INSERT INTO products (id, name, brand, price) VALUES (79, 'Mi 9T Pro', 'Xiaomi', 930);
INSERT INTO products (id, name, brand, price) VALUES (80, 'Zenfone 5Z', 'Asus', 800);
INSERT INTO products (id, name, brand, price) VALUES (81, 'Galaxy Z Flip 5G', 'Samsung', 720);
INSERT INTO products (id, name, brand, price) VALUES (82, 'V40 ThinQ', 'LG', 700);
INSERT INTO products (id, name, brand, price) VALUES (83, 'Xperia L3', 'Sony', 680);
INSERT INTO products (id, name, brand, price) VALUES (84, 'Find X', 'Oppo', 950);
INSERT INTO products (id, name, brand, price) VALUES (85, 'Black Shark 2 Pro', 'Xiaomi', 620);
INSERT INTO products (id, name, brand, price) VALUES (86, 'Galaxy S10e', 'Samsung', 930);
INSERT INTO products (id, name, brand, price) VALUES (87, 'ROG Phone', 'Asus', 690);
INSERT INTO products (id, name, brand, price) VALUES (88, 'Mate 20 Pro', 'Huawei', 960);
INSERT INTO products (id, name, brand, price) VALUES (89, 'Moto Z3', 'Motorola', 600);
INSERT INTO products (id, name, brand, price) VALUES (90, 'Mi 8', 'Xiaomi', 850);
INSERT INTO products (id, name, brand, price) VALUES (91, 'Zenfone 5', 'Asus', 660);
INSERT INTO products (id, name, brand, price) VALUES (92, 'Xperia XZ3', 'Sony', 790);
INSERT INTO products (id, name, brand, price) VALUES (93, 'Galaxy S9', 'Samsung', 700);
INSERT INTO products (id, name, brand, price) VALUES (94, 'V30 ThinQ', 'LG', 630);
INSERT INTO products (id, name, brand, price) VALUES (95, 'P20 Pro', 'Huawei', 710);
INSERT INTO products (id, name, brand, price) VALUES (96, 'Moto G6 Plus', 'Motorola', 690);
INSERT INTO products (id, name, brand, price) VALUES (97, 'Mi Mix 2', 'Xiaomi', 730);
INSERT INTO products (id, name, brand, price) VALUES (98, 'ROG Phone', 'Asus', 860);
INSERT INTO products (id, name, brand, price) VALUES (99, 'Mate 10 Pro', 'Huawei', 890);
INSERT INTO products (id, name, brand, price) VALUES (100, 'Galaxy Note8', 'Samsung', 900);
INSERT INTO products (id, name, brand, price) VALUES (101, 'iPhone SE (2020)', 'Apple', 620);
INSERT INTO products (id, name, brand, price) VALUES (102, 'Galaxy A32', 'Samsung', 690);
INSERT INTO products (id, name, brand, price) VALUES (103, 'Pixel 4a', 'Google', 600);
INSERT INTO products (id, name, brand, price) VALUES (104, 'Nova 7', 'Huawei', 690);
INSERT INTO products (id, name, brand, price) VALUES (105, 'Xperia 10 Plus', 'Sony', 760);
INSERT INTO products (id, name, brand, price) VALUES (106, 'Legion Phone Duel 2 Pro', 'Lenovo', 640);
INSERT INTO products (id, name, brand, price) VALUES (107, 'ROG Phone 6', 'Asus', 980);
INSERT INTO products (id, name, brand, price) VALUES (108, 'Mi Mix 4', 'Xiaomi', 730);
INSERT INTO products (id, name, brand, price) VALUES (109, 'G7 ThinQ', 'LG', 850);
INSERT INTO products (id, name, brand, price) VALUES (110, 'Nord CE', 'OnePlus', 820);
INSERT INTO products (id, name, brand, price) VALUES (111, 'Find X4 Pro', 'Oppo', 810);
INSERT INTO products (id, name, brand, price) VALUES (112, 'Poco F3', 'Poco', 810);
INSERT INTO products (id, name, brand, price) VALUES (113, 'Black Shark 5', 'Xiaomi', 970);
INSERT INTO products (id, name, brand, price) VALUES (114, 'Reno6 Pro+ 5G', 'Oppo', 630);
INSERT INTO products (id, name, brand, price) VALUES (115, 'Moto G Stylus (2021)', 'Motorola', 770);
INSERT INTO products (id, name, brand, price) VALUES (116, 'Galaxy A72', 'Samsung', 960);
INSERT INTO products (id, name, brand, price) VALUES (117, 'Zenfone 8 Pro', 'Asus', 820);
INSERT INTO products (id, name, brand, price) VALUES (118, 'Velvet 2 Pro', 'LG', 780);
INSERT INTO products (id, name, brand, price) VALUES (119, 'Xperia 1 IV', 'Sony', 610);
INSERT INTO products (id, name, brand, price) VALUES (120, 'Wing 6G', 'LG', 600);
INSERT INTO products (id, name, brand, price) VALUES (121, 'Galaxy Z Fold3', 'Samsung', 710);
INSERT INTO products (id, name, brand, price) VALUES (122, 'Surface Duo 3', 'Microsoft', 890);
INSERT INTO products (id, name, brand, price) VALUES (123, 'Legion 2 Pro', 'Lenovo', 820);
INSERT INTO products (id, name, brand, price) VALUES (124, 'ROG Phone 4', 'Asus', 630);
INSERT INTO products (id, name, brand, price) VALUES (125, 'Velvet 5G Pro', 'LG', 800);
INSERT INTO products (id, name, brand, price) VALUES (126, 'Xperia 20', 'Sony', 660);
INSERT INTO products (id, name, brand, price) VALUES (127, 'Galaxy Note21 Ultra', 'Samsung', 710);
INSERT INTO products (id, name, brand, price) VALUES (128, 'Moto G40', 'Motorola', 810);
INSERT INTO products (id, name, brand, price) VALUES (129, 'Mi Mix 5', 'Xiaomi', 680);
INSERT INTO products (id, name, brand, price) VALUES (130, 'Zenfone 8', 'Asus', 840);
INSERT INTO products (id, name, brand, price) VALUES (131, 'Galaxy Z Flip3', 'Samsung', 820);
INSERT INTO products (id, name, brand, price) VALUES (132, 'V70 ThinQ', 'LG', 920);
INSERT INTO products (id, name, brand, price) VALUES (133, 'Xperia 30', 'Sony', 640);
INSERT INTO products (id, name, brand, price) VALUES (134, 'Find X3 Lite', 'Oppo', 800);
INSERT INTO products (id, name, brand, price) VALUES (135, 'Black Shark 6', 'Xiaomi', 720);
INSERT INTO products (id, name, brand, price) VALUES (136, 'Galaxy S21 FE', 'Samsung', 690);
INSERT INTO products (id, name, brand, price) VALUES (137, 'ROG Phone 5 Pro', 'Asus', 810);
INSERT INTO products (id, name, brand, price) VALUES (138, 'Mate 50 Pro', 'Huawei', 940);
INSERT INTO products (id, name, brand, price) VALUES (139, 'Moto G Pure', 'Motorola', 740);
INSERT INTO products (id, name, brand, price) VALUES (140, 'Mi 11T Pro', 'Xiaomi', 990);
INSERT INTO products (id, name, brand, price) VALUES (141, 'Zenfone 8 Flip', 'Asus', 990);
INSERT INTO products (id, name, brand, price) VALUES (142, 'Xperia 2', 'Sony', 720);
INSERT INTO products (id, name, brand, price) VALUES (143, 'Galaxy Note22', 'Samsung', 610);
INSERT INTO products (id, name, brand, price) VALUES (144, 'Nord 3', 'OnePlus', 840);
INSERT INTO products (id, name, brand, price) VALUES (145, 'Find X4 Lite', 'Oppo', 630);
INSERT INTO products (id, name, brand, price) VALUES (146, 'Poco F4', 'Poco', 870);
INSERT INTO products (id, name, brand, price) VALUES (147, 'Black Shark 6 Pro', 'Xiaomi', 620);
INSERT INTO products (id, name, brand, price) VALUES (148, 'Reno7 Pro 5G', 'Oppo', 760);
INSERT INTO products (id, name, brand, price) VALUES (149, 'Moto G Power (2022)', 'Motorola', 960);
INSERT INTO products (id, name, brand, price) VALUES (150, 'Galaxy A73', 'Samsung', 690);
INSERT INTO products (id, name, brand, price) VALUES (151, 'Zenfone 9', 'Asus', 830);
INSERT INTO products (id, name, brand, price) VALUES (152, 'Velvet 3', 'LG', 710);
INSERT INTO products (id, name, brand, price) VALUES (153, 'Xperia 40', 'Sony', 680);
INSERT INTO products (id, name, brand, price) VALUES (154, 'Wing 7G', 'LG', 660);
INSERT INTO products (id, name, brand, price) VALUES (155, 'Galaxy Z Fold4', 'Samsung', 790);
INSERT INTO products (id, name, brand, price) VALUES (156, 'Surface Duo 4', 'Microsoft', 600);
INSERT INTO products (id, name, brand, price) VALUES (157, 'Legion 3 Pro', 'Lenovo', 870);
INSERT INTO products (id, name, brand, price) VALUES (158, 'ROG Phone 7', 'Asus', 670);
INSERT INTO products (id, name, brand, price) VALUES (159, 'Velvet 6G', 'LG', 650);
INSERT INTO products (id, name, brand, price) VALUES (160, 'Xperia 50', 'Sony', 790);
INSERT INTO products (id, name, brand, price) VALUES (161, 'Galaxy Note23 Ultra', 'Samsung', 770);
INSERT INTO products (id, name, brand, price) VALUES (162, 'Moto G60', 'Motorola', 980);
INSERT INTO products (id, name, brand, price) VALUES (163, 'Mi Mix 6', 'Xiaomi', 650);
INSERT INTO products (id, name, brand, price) VALUES (164, 'Zenfone 10', 'Asus', 940);
INSERT INTO products (id, name, brand, price) VALUES (165, 'Galaxy Z Flip4', 'Samsung', 650);
INSERT INTO products (id, name, brand, price) VALUES (166, 'V80 ThinQ', 'LG', 620);
INSERT INTO products (id, name, brand, price) VALUES (167, 'Xperia 60', 'Sony', 750);
INSERT INTO products (id, name, brand, price) VALUES (168, 'Find X4 Pro+', 'Oppo', 720);
INSERT INTO products (id, name, brand, price) VALUES (169, 'Black Shark 7', 'Xiaomi', 900);
INSERT INTO products (id, name, brand, price) VALUES (170, 'Galaxy S22', 'Samsung', 840);
INSERT INTO products (id, name, brand, price) VALUES (171, 'ROG Phone 6 Pro', 'Asus', 800);
INSERT INTO products (id, name, brand, price) VALUES (172, 'Mate 60 Pro', 'Huawei', 720);
INSERT INTO products (id, name, brand, price) VALUES (173, 'Moto G Stylus (2022)', 'Motorola', 820);
INSERT INTO products (id, name, brand, price) VALUES (174, 'Mi 12', 'Xiaomi', 950);
INSERT INTO products (id, name, brand, price) VALUES (175, 'Zenfone 11', 'Asus', 610);
INSERT INTO products (id, name, brand, price) VALUES (176, 'Xperia 70', 'Sony', 700);
INSERT INTO products (id, name, brand, price) VALUES (177, 'Wing 8G', 'LG', 790);
INSERT INTO products (id, name, brand, price) VALUES (178, 'Galaxy Z Fold5', 'Samsung', 820);
INSERT INTO products (id, name, brand, price) VALUES (179, 'Surface Duo 5', 'Microsoft', 970);
INSERT INTO products (id, name, brand, price) VALUES (180, 'Legion 4', 'Lenovo', 650);
INSERT INTO products (id, name, brand, price) VALUES (181, 'ROG Phone 8', 'Asus', 750);
INSERT INTO products (id, name, brand, price) VALUES (182, 'Velvet 7G', 'LG', 670);
INSERT INTO products (id, name, brand, price) VALUES (183, 'Xperia 80', 'Sony', 890);
INSERT INTO products (id, name, brand, price) VALUES (184, 'Galaxy Note24 Ultra', 'Samsung', 950);
INSERT INTO products (id, name, brand, price) VALUES (185, 'Nord 4', 'OnePlus', 920);
INSERT INTO products (id, name, brand, price) VALUES (186, 'Find X5', 'Oppo', 730);
INSERT INTO products (id, name, brand, price) VALUES (187, 'Poco F5', 'Poco', 790);
INSERT INTO products (id, name, brand, price) VALUES (188, 'Black Shark 8', 'Xiaomi', 770);
INSERT INTO products (id, name, brand, price) VALUES (189, 'Reno8 Pro 5G', 'Oppo', 940);
INSERT INTO products (id, name, brand, price) VALUES (190, 'Moto G Pro (2023)', 'Motorola', 920);
INSERT INTO products (id, name, brand, price) VALUES (191, 'Galaxy A83', 'Samsung', 780);
INSERT INTO products (id, name, brand, price) VALUES (192, 'Zenfone 12', 'Asus', 770);
INSERT INTO products (id, name, brand, price) VALUES (193, 'Xperia 90', 'Sony', 760);
INSERT INTO products (id, name, brand, price) VALUES (194, 'Wing 9G', 'LG', 640);
INSERT INTO products (id, name, brand, price) VALUES (195, 'Galaxy Z Flip6', 'Samsung', 780);
INSERT INTO products (id, name, brand, price) VALUES (196, 'Surface Duo 6', 'Microsoft', 950);
INSERT INTO products (id, name, brand, price) VALUES (197, 'Legion 5A', 'Lenovo', 930);
INSERT INTO products (id, name, brand, price) VALUES (198, 'ROG Phone 9', 'Asus', 750);
INSERT INTO products (id, name, brand, price) VALUES (199, 'Velvet 8G', 'LG', 610);
INSERT INTO products (id, name, brand, price) VALUES (200, 'Xperia 100', 'Sony', 850);